### ISSUE TITLE
Semvar and Release Cycle

### ISSUE THREAD

**Issue by lykinsbd** [tbotnz/cisshgo#16]
We probably need to get up to the v1.0.0 release and start strictly following semvar with any pushes to master.  With Go modules this can really bite you in the behind later if you don't start early.

I don't _anticipate_ too many people would be importing our code as a module, vs running the standalone application, but you never know.

**Comment by tbotnz** [comment]
Agree,

Are you happy with the stability of the current codebase vs any features you have in mind?

**Comment by lykinsbd** [comment]
I want to get some type of multi device selection in place before v1.0.  We could probably go ahead and continue the v0.x.y train for now. Just stick with a release per merge to master and follow semvar within v0.
